openapi: 3.0.1
info:
  title: vsCodeTestMvnApi
  description: API Definition of vsCodeTestMvnApi
  version: 1.0.0
servers:
- url: http://localhost:8290/vscodetestmvnapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
